namespace SistemaTriagemManchester.Apresentacao.UI.Manager
{
    public enum UserControlEnum
    {
        UcCadastroSenhaUsuario,
        UcCadastroUsuario,
        UcCadastro,
        UcCadastroPaciente,
        UcConsultaPaciente,
        UcAtendimentoDiagnostico,
        UcAtendimentoExameFisico,
        UcAtendimentoIdentificacaoPaciente,
        UcAtendimentoPaciente,
        UcAtendimentoPacienteHistorico,
        UcAtendimentoPlanoTratamento,
        UcConclusaoAtendimento,
        UcFilaAtendimentoPaciente,
        UcDashboard,
        UcHistorico,
        UcHistoricoConsultas,
        UcHistoricoExames,
        UcHistoricoIdentificacaoPaciente,
        UcHistoricoTriagens,
        UcRelatorio,
        UcTriagemPaciente,
        UcConfiguracao,
        UcAcolhimento
    }
}
